"""Добавил админа пользователяю

Revision ID: 478703c75bdf
Revises: 41fc7e53f06e
Create Date: 2026-06-27 14:30:05.527588

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "478703c75bdf"
down_revision: Union[str, Sequence[str], None] = "41fc7e53f06e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
